# Generated by Django 6.0.4 on 2026-04-28 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
