# Generated by Django 6.0.3 on 2026-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapz", "0003_comment_created_at_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
