# Generated by Django 6.0.3 on 2026-04-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapz", "0004_alter_comment_created_at_alter_like_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapz",
            name="image",
        ),
        migrations.CreateModel(
            name="SnapzImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="snapz_image")),
                (
                    "snapz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snapz.snapz"
                    ),
                ),
            ],
        ),
    ]
