# Generated by Django 6.0.3 on 2026-04-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapz", "0005_remove_snapz_image_snapzimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapzimage",
            old_name="image",
            new_name="images",
        ),
        migrations.AlterField(
            model_name="snapzimage",
            name="snapz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="snapz.snapz",
            ),
        ),
    ]
