# Generated by Django 6.0.3 on 2026-04-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snapz", "0006_rename_image_snapzimage_images_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapzimage",
            old_name="images",
            new_name="image",
        ),
    ]
